### ISSUE TITLE
Cannot configure settings

### ISSUE THREAD

**Issue by longgtruong** [gianlucaparadise/strapi-plugin-vercel-deploy#12] opened 2022-12-12 14:00 UTC
I have include all the configs in `config/plugins.js` but nothing seems to change on the settings or Vercel Deploy page.

**Comment by barrynorman** [comment] 2022-12-15 13:29
Hi @longgtruong 
Can you show some code? Then I might help you. Just installed and used it

**Comment by Nick87** [comment] 2022-12-27 10:38
Same problem here:

This is my config/plugin.js:

![image](https://user-images.githubusercontent.com/1497044/209654152-2ae790b4-d6e4-46da-8c24-88ba59ea665a.png)

and this is what strapi says:

![image](https://user-images.githubusercontent.com/1497044/209654223-125ca20b-2cb9-40c7-8085-c3509a948dfa.png)

![image](https://user-images.githubusercontent.com/1497044/209654267-9f46a572-a4c9-41c4-b5ea-51ce8affaff8.png)

**Comment by mrhoodz** [comment] 2022-12-27 10:44
Im also bumping into this issue

**Comment by Nick87** [comment] 2022-12-30 13:26
@barrynorman did you manage to reproduce the issue?

**Comment by barrynorman** [comment] 2023-01-01 16:33
@Nick87 @longgtruong 
Which version of the plugin do you use?

Here is my config. Can you please try to add "appFilter" and "teamFilter" to your config. Not sure if they are mandatory but just to be sure this is not the issue. 

And I'm personally using the "env" to pass the vars to the config, but this should not cause any issues.

**Comment by gianlucaparadise** [comment] 2023-01-02 13:33
@Nick87 Is the `users-permissions` plugin working? As per official documentation, the config entries for the plugins should be in a file under `./config/plugins.js` and not `plugin.js` (please note the missing _s_ in the file name). Reference is [here](https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/plugins.html). 

To be 100% sure that Strapi is reading your config file, please try to:
- Set `enabled: false` for `"vercel-deploy"` configs
- Rebuild using `yarn build`
- Re-run using `yarn start`
- Refresh the admin console
- Verify that _Vercel Deploy_ is not displayed in the sidebar or in the configurations

I reproduced your issue using `plugin.js` as file name and fixed the issue using `plugins.js`.

@longgtruong @mrhoodz Can you please double check your file name, too? Otherwise I need more info to look into this issue because I need to be able to replicate it.

**Comment by Nick87** [comment] 2023-01-02 14:28
@barrynorman renaming `plugin.js` in `plugins.js` under `./config` did the trick, I did not notice the file name difference: I must have created the file with the wrong name the first time around.

Thanks for your time and help! :)

**Comment by gianlucaparadise** [comment] 2023-03-02 06:48
Closing issue for missing info.

**Closed by gianlucaparadise** 2023-03-02 06:48 UTC
Labels: question
